// Lista completa de exames extraída de labpaulistarc.com.br — A a Z
export const EXAMES_LISTA: string[] = [
  // A
  "Acanthamoeba",
  "Acetilcolinesterase Eritrocitária",
  "Acetona no Sangue",
  "Acetona Urinária",
  "Ácido 5 Hidroxi Indol Acético",
  "Ácido Cítrico – Esperma",
  "Ácido Delta Aminolevulínico",
  "Ácido Fólico",
  "Ácido Hipúrico",
  "Ácido Homovanílico",
  "Ácido Lático",
  "Ácido Metilhipúrico",
  "Ácido Metilmalônico – Soro",
  "Ácido Metilmalônico – Urina",
  "Ácido Trans-Trans Mucônico",
  "Ácido Tricloroacético",
  "Ácido Úrico",
  "Ácido Úrico em Urina 24 Horas",
  "Ácido Úrico Urinário",
  "Ácido Valpróico",
  "Ácido Vanil Mandélico",
  "Ácido Vanil Mandélico – Urina 24h",
  "Ácido-Mandélico",
  "Ácidos Biliares",
  "Ácidos Graxos de Cadeia Muito Longa",
  "Ácidos Graxos – Pesquisa",
  "Ácidos Orgânicos",
  "Ácidos Orgânicos em Urina",
  "Acilcarnitinas Urinárias",
  "Acilcarnitinas",
  "ADAMTS-13 (Atividade da Protease de Ruptura de Fator de Von Willebrand)",
  "Adenograma",
  "Adenosina Deaminase",
  "Adenosina Deaminase – Líquido Pleural",
  "Adenovírus",
  "Adiponectina",
  "ACTH – Adrenocorticotrófico",
  "Albumina",
  "Aldolase",
  "Aldosterona",
  "Aldosterona Urinária 24 Horas",
  "Alfa 1 Anti-Tripsina",
  "Alfa 1 Anti-Tripsina - Fezes",
  "Alfa 1 Glicoproteína Ácida",
  "Alfa Androstanediol Glucoronide",
  "Alfa Hidroxiprogesterona",
  "Alfa Hidroxiprogesterona – Neonatal",
  "Alfafetoproteína",
  "Apolipoproteína A-I",
  "Apolipoproteína B",
  "Apolipoproteína E",
  "Alumínio",
  "Alumínio Urinário",
  "Amilase / Amilase Isoenzimas / Amilase Pancreática",
  "Amilase Salivar",
  "Amilase Urinária",
  "Aminoacidopatias e Acidemias Orgânicas",
  "Aminoácidos Séricos Quantitativos",
  "AMP Cíclico",
  "ANCA – Anticorpos Anti-Citoplasma de Neutrófilos C e P",
  "Androstenediona",
  "Anfetamina",
  "Angiotensina – Enzima Conversora (ECA)",
  "Anti-Beta2 Glicoproteína IgG e IgM",
  "Anti-Nucleossomo / Anti-Cromatina",
  "Anti-Saccharomyces Cerevisiae – IgA e IgG",
  "Anti-SCL-70",
  "Anti-SM",
  "Anti-SS-A (Ro)",
  "Anti-SS-B (La)",
  "Anti-Transglutaminase IgA",
  "Anti-Transglutaminase IgG",
  "Anti-Trombina III",
  "Anti Estreptolisina O (ASLO)",
  "Anti Gliadina – Anticorpos IgA",
  "Anti Gliadina – Anticorpos IgG",
  "Anti Mitocôndria",
  "Anti-DNA (Dupla Hélice) ou Nativo",
  "Anti-Endomísio – Anticorpos IgA",
  "Anti-Endomísio – Anticorpos IgG",
  "Anti-Fosfolipase A2",
  "Anti-Fração Microssomal de Fígado e Rim",
  "Anti-Tireoglobulina",
  "Anti-TPO – Anticorpos Anti-Peroxidase",
  "Antibiograma",
  "Anticoagulante Lúpico",
  "Anticorpo Anti-Aquaporina 4 IgG",
  "Anticorpo Anti-Músculo Cardíaco",
  "Anticorpo Anti-Receptor de Acetilcolina",
  "Anticorpos Anti-Canal de Cálcio",
  "Anticorpos Anti-Fator Intrínseco",
  "Anticorpos Anti-21-Hidroxilase Alfa",
  "Anticorpos Anti-Borrelia Burgdorferi",
  "Anticorpos Anti-Campylobacter Jejuni",
  "Anticorpos Anti-Candida Albicans",
  "Anticorpos Anti-Cardiolipina (IgG, IgM e IgA)",
  "Anticorpos Anti-Centrômero",
  "Anticorpos Anti-Chikungunya IgG e IgM",
  "Anticorpos Anti-Citrulina",
  "Anticorpos Anti-Colágeno Tipo II",
  "Anticorpos Anti-Entamoeba Histolytica",
  "Anticorpos Anti-Gangliosídeos",
  "Anticorpos Anti-Granulócitos",
  "Anticorpos Anti-Insulina",
  "Anticorpos Anti-Músculo Liso",
  "Anticorpos Anti-Neuronais",
  "Anticorpos Anti-Ovário",
  "Anticorpos Anti-Plaquetas",
  "Anticorpos Anti-Pneumococos",
  "Anticorpos Anti-Proteínase 3",
  "Anticorpos Anti-Ribossomas",
  "Anticorpos Anti-RNA Polimerase I",
  "Anticorpos Anti-Strongyloides Stercoralis",
  "Anticorpos Anti-Supra Renal e Córtex Adrenal",
  "Anticorpos Anti-YO / Anti-Células de Purkinje",
  "Anticorpos Anti-Espermatozóide",
  "Anticorpos Anti-Actina",
  "Anticorpos Anti-Células Parietais",
  "Anticorpos Anti-Cocleares",
  "Anticorpos Anti-Fator VIII – Quantificação",
  "Anticorpos Anti-GAD",
  "Anticorpos Anti-Ilhotas de Langerhans",
  "Anticorpos Anti-MAG",
  "Anticorpos Anti-Peptídeo Citrulinado",
  "Anticorpos Anti-Receptor de Insulina",
  "Anticorpos Anti-Rubéola IgG",
  "Anticorpos Anti-Rubéola IgM",
  "Anticorpos Anti-Tétano",
  "Anticorpos Neutralizantes SARS-CoV2",
  "Anticorpos Influenza A e B",

  // B
  "BAAR – Pesquisa",
  "Bacterioscopia",
  "Bacterioscopia – Secreção Vaginal",
  "Bacterioscopia Urina",
  "Bartonella – Anticorpos",
  "Benzodiazepínicos",
  "Beta-2 Microglobulina",
  "Beta-2 Microglobulina Urinária",
  "Beta-HCG – Gonadotrofina Coriônica (Quantitativo)",
  "Bilirrubinas Total e Frações",
  "Biópsia – Histopatológico",
  "Biópsia – Histopatológico de Medula Óssea",
  "BRAF – Detecção da Mutação V600E",
  "BRCA1 – Detecção de Mutação",
  "BRCA1 – Sequenciamento",
  "BRCA2 – Detecção de Mutação",
  "Brometo",
  "Brucelose",

  // C
  "CA 125",
  "CA 15-3",
  "CA 19-9",
  "CA 242",
  "CA 27-29",
  "CA 50",
  "CA 72-4",
  "Cádmio – Sanguíneo",
  "Cádmio Urinário",
  "Cafeína",
  "Cálcio",
  "Cálcio Ionizado",
  "Cálcio Urinário",
  "Cálcio Urinário 24 Horas",
  "Calcitonina",
  "Cálculo Renal (Urinário)",
  "Calprotectina",
  "Canabinóides (Maconha)",
  "Candida – Anticorpos IgG",
  "Candida – Anticorpos IgM",
  "Carbamazepina",
  "Carboxihemoglobina",
  "Cardiolipina IgA",
  "Cardiolipina IgG",
  "Cardiolipina IgM",
  "Cariótipo Banda G",
  "Cariótipo de Material de Aborto",
  "Cariótipo de Medula",
  "Cariótipo X Frágil",
  "Carnitina Total e Livre",
  "Catecolaminas Livres",
  "Catecolaminas Plasmáticas",
  "Catecolaminas Urinárias",
  "Caxumba IgG",
  "Caxumba IgM",
  "CEA – Antígeno Carcinoembrionário",
  "Ceruloplasmina",
  "Chagas – Hemaglutinação",
  "Chagas – Imunofluorescência Indireta IgG",
  "Chagas – Imunofluorescência Indireta IgM",
  "Chikungunya – PCR",
  "Chlamydia – IgA",
  "Chlamydia – Sorologia IgG",
  "Chlamydia – Sorologia IgM",
  "Chlamydia Pneumoniae – Detecção por PCR",
  "Chlamydia Trachomatis e Neisseria Gonorrhoeae – PCR",
  "Chumbo (Sangue)",
  "Chumbo – Urina",
  "Ciclosporina",
  "Cistatina C",
  "Citograma Nasal",
  "Citologia Oncótica (Papanicolaou)",
  "Citomegalovírus – Anticorpo IgG",
  "Citomegalovírus – Anticorpo IgM",
  "Citomegalovírus – Detecção por PCR",
  "Citomegalovírus – Avidez IgG",
  "Citomegalovírus – Quantificação (Carga Viral)",
  "Citometria de Fluxo (Imunofenotipagem) – Medula Óssea",
  "Citometria de Fluxo (Imunofenotipagem) – Sangue Total",
  "Citrato Urinário 24h",
  "Clonazepam (Rivotril)",
  "Cloreto",
  "Cloreto na Urina",
  "Clostridium Difficile – Detecção por PCR",
  "Clostridium Difficile – Toxina A + B",
  "Coagulograma",
  "Cobalto",
  "Cobalto Urinário",
  "Cobre",
  "Cobre Urinário",
  "Cocaína (Pesquisa na Urina)",
  "Coenzima Q10",
  "Colesterol HDL",
  "Colesterol LDL",
  "Colesterol Total",
  "Colesterol Total e Frações",
  "Colesterol VLDL",
  "Colinesterase",
  "Complemento C3",
  "Complemento C4",
  "Complemento Total – CH50",
  "Contagem de Plaquetas",
  "Contagem de Reticulócitos",
  "Contagem de Linfócitos CD4",
  "Contagem de Linfócitos CD8",
  "Coombs Direto",
  "Coombs Indireto",
  "Coprocultura",
  "Coprológico Funcional",
  "COVID-19 – Detecção por PCR",
  "COVID-19 – Sorologia (ELISA/Quimioluminescência)",
  "Cortisol",
  "Creatina Quinase – CK",
  "Creatinina",
  "Cultura e Antibiograma – Fezes",
  "Cultura e Antibiograma – Mycoplasma/Ureaplasma",
  "Cultura e Antibiograma – Neisseria",
  "Cultura e Antibiograma – Secreção Orofaringe",
  "Cultura e Antibiograma – Secreção Uretral",
  "Cultura e Antibiograma – Secreção Vaginal",
  "Cultura e Antifungigrama",

  // D
  "D-Dímero",
  "D-Xilose",
  "DHEA – Dehidroepiandrosterona",
  "DHEA-S – Dehidroepiandrosterona Sulfato",
  "Dengue",
  "Desidrogenase Lática – LDH",
  "Desoxicortisol",
  "DHT – Di-Hidrotestosterona",
  "Digoxina",
  "Distrofia Muscular Duchenne/Becker",
  "Doença Celíaca",
  "Dosagem de Amilase Urinária",

  // E
  "Elastase Pancreática",
  "Eletroforese de Hemoglobina",
  "Eletroforese de Hemoglobina com Confirmação por HPLC",
  "Eletroforese de Lipoproteínas",
  "Eletroforese de Proteínas",
  "Eletroforese de Proteínas – Urina",
  "Entamoeba Histolytica",
  "Enterobius Vermicularis (Oxiúrus)",
  "Enterovírus – Detecção por PCR",
  "Enzima Conversora de Angiotensina – ECA",
  "Eosinófilos – Fezes",
  "Eosinófilos – Urina",
  "Epstein-Barr – Anticorpos IgG",
  "Eritropoetina",
  "Erros Inatos do Metabolismo",
  "Espermocultura",
  "Espermograma",
  "Estradiol – E2",
  "Estriol",
  "Estrona",
  "Estudo Cromossômico",
  "Estudo de Intolerância Alimentar",
  "Estudo Molecular de Alfa-Talassemia",
  "Estudo Molecular CGH Array",
  "Estudo Molecular – Coreia de Huntington",
  "Estudo Molecular – Atrofia Muscular Espinhal (SMN1, SMN2)",
  "Etanol",

  // F
  "Falcização de Hemácias",
  "FAN – Fator Antinuclear",
  "Farmacogenética Onco – 5-Fluorouracil",
  "Farmacogenética Onco – Cisplatina",
  "Farmacogenética Onco – Irinotecan",
  "Farmacogenética Onco – Metotrexato",
  "Farmacogenética Onco – Tamoxifeno",
  "Fator de Necrose Tumoral Alfa",
  "Fator de Von Willebrand",
  "Fator II",
  "Fator IX",
  "Fator Reumatoide",
  "Fator Rh",
  "Fator V de Leiden – Pesquisa da Mutação",
  "Fator VII",
  "Fator VIII",
  "Fator XI",
  "Fator XII",
  "Fator XIII",
  "Febre Amarela",
  "Febre Maculosa – Anticorpos IgG e IgM",
  "Febre Mediterrânea",
  "Fenilalanina – PKU",
  "Fenitoína",
  "Fenobarbital",
  "Fenol Urinário",
  "Fenotipagem Eritrocitária Estendida",
  "Ferritina",
  "Ferro Sérico",
  "Ferro Urinário",
  "Fibrinogênio",
  "Fibrose Cística – Pesquisa de Mutação",
  "Fosfatase Ácida Prostática",
  "Fosfatase Ácida Total",
  "Fosfatase Alcalina",
  "Fosfatase Alcalina – Isoenzimas",
  "Fosfatase Alcalina Óssea",
  "Fosfolipídios",
  "Fósforo",
  "Fósforo Urinário 24 Horas",
  "Frutosamina",
  "FSH – Folículo Estimulante",
  "FTA-ABS (Sífilis)",
  "Fungos – Pesquisa",

  // G
  "Gama Glutamil Transferase – GGT",
  "Gastrina",
  "Genotipagem – Hepatite C",
  "Genotipagem para HIV",
  "Giárdia",
  "Glicemia de Jejum",
  "Glicose – Curva Glicêmica e Pós-Prandial",
  "Glicose 6 Fosfato Desidrogenase",
  "Glicosúria",
  "Glucagon",
  "Gordura Fecal",
  "Grupo Sanguíneo e Fator Rh",

  // H
  "H1N1",
  "Haptoglobina",
  "HCG – Gonadotrofina Coriônica",
  "Helicobacter Pylori",
  "Helicobacter Pylori – Anticorpos IgA",
  "Helicobacter Pylori – Anticorpos IgG",
  "Helicobacter Pylori – Anticorpos IgM",
  "Hematócrito",
  "Hemocromatose – C282Y, H63D e S65C",
  "Hemocultura Automatizada",
  "Hemofilia A (F8) – Sequenciamento",
  "Hemofilia B (F9) – Sequenciamento",
  "Hemoglobina",
  "Hemoglobina A2",
  "Hemoglobina Fetal",
  "Hemoglobina Glicada (HbA1c)",
  "Hemograma",
  "Heparina Circulante",
  "Hepatite A – Anti-HVA",
  "Hepatite B – Anti-HBc Total",
  "Hepatite B – HBeAg",
  "Hepatite B – HBsAg (Antígeno Austrália)",
  "Hepatite C – Anti-HCV",
  "Hepatite C – Genotipagem",
  "Hepatite C – Quantificação por PCR",
  "Hepatite D",
  "Hepatite E",
  "Herpes 1 e 2 – IgG",
  "Herpes 1 e 2 – IgM",
  "Herpes Simplex 1 e 2 – Detecção por PCR",
  "Herpes 6 – Detecção por PCR",
  "HIV – Antígeno P24",
  "HIV – Qualitativo",
  "HIV – Quantificação por PCR (Carga Viral)",
  "HIV – Western Blot",
  "HIV 1 – Genotipagem (Resistência)",
  "HIV 1 e 2 – Antígeno e Anticorpos (Triagem)",
  "HLA-B27 – Detecção por PCR",
  "HLA-DQ2 e DQ8 – Doença Celíaca",
  "Homocisteína",
  "Hormônio Anti-Mülleriano",
  "Hormônio Antidiurético (ADH)",
  "Hormônio do Crescimento – HGH",
  "Hormônio Folículo Estimulante – FSH",
  "Hormônio Luteinizante – LH",
  "HTLV I/II – Anticorpos",

  // I
  "IgE Total",
  "IgE Específico – Painel de Alimentos",
  "IgE Específico – Ácaros",
  "IgE Específico – Gramíneas",
  "IgE Específico – Pólens",
  "IgE Específico – Fungos",
  "IGF-1 – Somatomedina C",
  "Imunofenotipagem – Neoplasia Hematológica",
  "Imunofixação de Proteínas Séricas",
  "Imunofixação de Proteínas em Urina 24h",
  "Imunoglobulinas – IgA, IgG, IgM",
  "Índice de Saturação da Transferrina",
  "Inibidor C1 Esterase",
  "Inibidora B",
  "Insulina",
  "Insulina Pós-Dextrosol",
  "Interleucina 6",
  "Intolerância Alimentar",
  "Iodo",
  "Iodo – Urina 24 Horas",

  // K
  "K-RAS – Mutação (Códons 12, 13 e 61)",
  "Kappa – Cadeia Leve",

  // L
  "Lactoferrina",
  "Lambda – Cadeia Leve",
  "Lamotrigina",
  "LDH – Lactato Desidrogenase",
  "LDL Oxidada",
  "Legionella – Pesquisa de Antígeno",
  "Leishmania Donovani",
  "Leptina",
  "Leptospirose – Anticorpos IgG",
  "Leptospirose – Anticorpos IgM",
  "Leucograma Completo",
  "Levetiracetam",
  "LH – Hormônio Luteinizante",
  "Linfócitos CD4",
  "Linfócitos CD8",
  "Linfócitos T e B – CD3/CD19",
  "Lipase",
  "Lipídios Totais",
  "Lipoproteína – Lpa",
  "Líquido Cefalorraquidiano – LCR",
  "Líquido Pleural",
  "Líquido Sinovial",
  "Lítio",

  // M
  "Maconha – Canabinóides",
  "Macroamilase",
  "Macroprolactina",
  "Magnésio",
  "Magnésio Eritrocitário",
  "Magnésio Urinário 24 Horas",
  "Malária",
  "Manganês",
  "Melatonina",
  "Mercúrio",
  "Mercúrio Urinário",
  "Metahemoglobina",
  "Metanefrina",
  "Metanefrinas Fracionadas – Plasma",
  "Metotrexato",
  "Micológico Direto",
  "Microalbuminúria",
  "Microalbuminúria – 24 Horas",
  "Microdeleção no Cromossomo Y",
  "Mielograma",
  "Mioglobina",
  "Mononucleose – Anticorpos Heterófilos",
  "Morfina",
  "Morfologia Estrita de Kruger",
  "MTHFR – Mutações C677T e A1298C",
  "Mucopolissacaridose",
  "Mutação V617F no Gene JAK-2",
  "Mycoplasma Hominis",

  // N
  "Neisseria Gonorrhoeae",
  "Neisseria Gonorrhoeae – PCR",
  "Neuroblastoma – Ácido Vanil Mandélico (VMA)",
  "Norovírus – Detecção por PCR",
  "NS1 – Antígeno do Vírus da Dengue",
  "NTX – Telopeptídeo",

  // O
  "Osmolalidade Sérica",
  "Osmolaridade Urinária",
  "Osteocalcina",
  "Oxalato",
  "Oxcarbazepina",
  "Oxiúrus",

  // P
  "Papanicolaou (Colpocitologia Oncótica)",
  "HPV – Papilomavírus Humano",
  "PAPP-A – Proteína A Plasmática",
  "Parasitológico de Fezes",
  "PTH – Paratormônio",
  "Parvovírus",
  "Peptídeo C",
  "Peptídeo Natriurético",
  "Perfil Lipídico (Lipidograma)",
  "Pesquisa de Alfa-Talassemia",
  "Pesquisa de Mutação no Gene NPM1",
  "Pesquisa de Vírus Respiratórios",
  "Piridinolina",
  "PKU – Fenilcetonúria",
  "Pneumocystis",
  "Potássio (K)",
  "Potássio Urinário 24 Horas",
  "Pregnenolona",
  "Primidona",
  "Pró-Insulina",
  "Procalcitonina",
  "Progesterona",
  "Prolactina",
  "Proteína Bence Jones",
  "Proteína C – Antigênica",
  "Proteína C – Funcional",
  "Proteína C Reativa – Ultrassensível",
  "Proteína S – Antigênica",
  "Proteína S – Funcional",
  "Proteína Urinária 24 Horas",
  "Proteínas Totais e Frações",
  "PSA Total – Antígeno Prostático Específico",
  "PSA Total / Livre",

  // Q
  "Quimerismo",

  // R
  "Raiva – Sorologia",
  "RAST – IgE Específico",
  "Rearranjo Gênico BCR/ABL",
  "Relação Proteína/Creatinina",
  "Renina (Atividade)",
  "Rotavírus – Pesquisa",
  "Rubéola – Anticorpos IgG",
  "Rubéola – Anticorpos IgM",
  "Rubéola – Avidez IgG",

  // S
  "Sangue Oculto nas Fezes",
  "Sarampo – Anticorpos IgG",
  "Sarampo – Anticorpos IgM",
  "Schistossomose",
  "Selênio Sérico",
  "Serotonina Sérica",
  "Serotonina Urinária",
  "Sexagem Fetal",
  "SHBG – Globulina Ligadora de Hormônios Sexuais",
  "Sífilis – VDRL",
  "Sirolimus",
  "Sódio",
  "Sódio Urinário",
  "Somatomedina C – IGF-1",
  "Soro Amilóide A",
  "Sorologia para Toxocaríase IgG e IgM",
  "Streptococcus Agalactiae (Grupo B)",
  "Subclasses de IgG",

  // T
  "T3 – Triiodotironina",
  "T3 – Triiodotironina Livre",
  "T3 – Triiodotironina Reverso",
  "T4 – Tiroxina",
  "T4 – Tiroxina Livre",
  "Tacrolimus (Prograf)",
  "Tempo de Atividade de Protrombina – TAP",
  "Tempo de Trombina",
  "Tempo de Tromboplastina Parcial Ativado – TTPA",
  "Teofilina",
  "Teste de Paternidade (DNA)",
  "Teste de Paternidade Duo",
  "Teste de Tolerância à Lactose",
  "Teste Genético de Intolerância à Lactose",
  "Teste de Fragmentação do DNA Espermático",
  "Testosterona Biodisponível",
  "Testosterona Livre",
  "Testosterona Total",
  "TGO – Aspartato Aminotransferase",
  "TGP – Alanina Aminotransferase",
  "Tireoglobulina",
  "Topiramato",
  "Toxicológico",
  "Toxoplasmose",
  "Toxoplasmose – Avidez IgG",
  "TRAb – Anticorpos Anti-Receptor de TSH",
  "Transferrina",
  "Triagem Neonatal – Aminoacidopatias (Tandem)",
  "Triagem Toxicológica",
  "Trichomonas Vaginalis",
  "Triglicerídeos",
  "Triptase",
  "TSH – Hormônio Tireoestimulante",

  // U
  "Ureia",
  "Ureia Urinária 24 Horas",
  "Urina Tipo I",
  "Urobilinogênio",
  "Urocultura e Antibiograma",
  "Urocultura e Antibiograma com Contagem de Colônias",

  // V
  "Varicela Zoster – Anticorpos IgG",
  "Varicela Zoster – Anticorpos IgM",
  "Vasopressina (ADH)",
  "VDRL – Sífilis Quantitativo",
  "Velocidade de Hemossedimentação – VHS",
  "Vírus da Dengue – Antígeno NS1",
  "Vitamina A",
  "Vitamina B1 (Tiamina)",
  "Vitamina B12",
  "Vitamina B2 (Riboflavina)",
  "Vitamina B6",
  "Vitamina C",
  "Vitamina D – 25 Hidroxi",
  "Vitamina D – 1,25 Di-Hidroxi",
  "Vitamina E",
  "Vitamina K",

  // W
  "Waaler Rose",
  "Western Blot – HIV",
  "Widal – Reação",

  // Y
  "Yersinia Enterocolitica",

  // Z
  "Zika Vírus",
  "Zika Vírus – Detecção por PCR",
  "Zika Vírus – Anticorpos IgG",
  "Zinco Sérico",
  "Zinco Eritrocitário",
  "Zinco Urinário 24 Horas",
];
